version: '3'

services:
  base: &app_base
    image: ${CONTAINER_TAG:-quay.io/wework/bp-we-eat:master}
    environment:
      - DATABASE_URL=postgres://postgres:R0tate1@pg/
      - RAILS_ENV=test
    volumes:
      - ${PWD}:/app
      - bp-we-eat-gems:/usr/local/bundle
      - bp-we-eat-spring:/tmp/spring-0
    tty: true
    stdin_open: true

  spring:
    <<: *app_base
    command: spring server

  test:
    <<: *app_base
    depends_on:
      - pg
    command: bin/rspec

  pg:
    image: postgres:10.5
    environment:
      - POSTGRES_PASSWORD=R0tate1
      - POSTGRES_DB=bp-we-eat_test

  # Because you should care about security
  brakeman:
    <<: *app_base
    command: brakeman -o brakeman-output.html

  # Because we all have opinions about code
  rubocop:
    <<: *app_base
    command: rubocop -f html -o rubocop.html

volumes:
  bp-we-eat-gems:
    external: true
  bp-we-eat-spring:
    external: true
