version: 2
defaults:
  docker_config: &docker_config
    docker:
        - image: circleci/buildpack-deps
    environment:
        - DOCKER_REGISTRY: 'quay.io/wework'
        - DOCKER_REPOSITORY: 'quay.io/wework/bp-we-eat'
  machine_config: &machine_config
    machine: true
    environment:
      - COMPOSE_FILE: 'docker-compose.test.yml'
      - DOCKER_REGISTRY: 'quay.io/wework'
      - DOCKER_REPOSITORY: 'quay.io/wework/bp-we-eat'
jobs:
  build:
    <<: *docker_config
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: DockerLogin
          command: .circleci/docker_login
      - run:
          name: CIBuild
          command: script/ci/build
  deploy:
    <<: *docker_config
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Login
          command: .circleci/docker_login
      - run:
          name: Install heroku-client
          command: |
            wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Heroku:Container Login
          command: heroku container:login
      - run:
          name: Deploy (Staging)
          command: |
            script/ci/deploy PROJECT-staging $(.circleci/full_tag)
      - run:
          name: Deploy (Production)
          command: |
            script/ci/deploy PROJECT-prod $(.circleci/full_tag)
  test:
    <<: *machine_config
    steps:
      - checkout
      - run:
          name: Setup
          command: script/ci/setup
      - run:
          name: CITest
          command: |
            export CONTAINER_TAG=$(.circleci/full_tag)
            script/test

  brakeman:
    <<: *machine_config
    steps:
      - checkout
      - run:
          name: Setup
          command: script/ci/setup
      - run:
          name: Brakeman
          command: |
            export CONTAINER_TAG=$(.circleci/full_tag)
            docker-compose run brakeman
      - store_artifacts:
          path: brakeman-output.html

  rubocop:
    <<: *machine_config
    steps:
      - checkout
      - run:
          name: Setup
          command: script/ci/setup
      - run:
          name: Rubocop
          command: |
            export CONTAINER_TAG=$(.circleci/full_tag)
            docker-compose run rubocop
      - store_artifacts:
          path: rubocop.html

workflows:
  version: 2
  cibuild:
    jobs:
      - build:
          context: org-global
      - test:
          context: org-global
          requires:
            - build
      - brakeman:
          context: org-global
          requires:
            - build
      - rubocop:
          context: org-global
          requires:
            - build
      # Uncomment to enable CD - merging to master will deploy built containers to staging and production
      # - deploy:
      #     context: org-global
      #     requires:
      #       - build
      #       - brakeman
      #       - rubocop
      #     filters:
      #       branches:
      #         only:
      #           - master
