module GetCuisineIcon
  @cuisine_to_icon_hash = {
    American: '🇺🇸',
    Asian: '🍙',
    Bakery: '🍞',
    Afghani: '🇦🇫',
    African: '🌍',
    Amish: '👨🏼‍🌾',
    Argentine: '🇦🇷',
    Armenian: '🇦🇲',
    Australian: '🇦🇺',
    Austrian: '🇦🇹',
    BBQ: '🍖',
    Bagels: '🥖',
    :"Bar Food" => '🍷',
    Belgian: '🇧🇪',
    Beverages: '🍻',
    Brazilian: '🇧🇷',
    Breakfast: '🍳',
    British: '🇬🇧',
    :"Bubble Tea" => '🍵',
    Burger: '🍔',
    Burmese: '🇲🇲',
    Cafe: '☕️',
    Cajun: '🍅',
    California: '🍅',
    Cambodian: '🇰🇭',
    Canadian: '🇨🇦',
    Cantonese: '🥜',
    Caribbean: '⛵️',
    :"Central Asian" => '🍜',
    Chilean: '🇨🇱',
    Chinese: '🇨🇳',
    :"Coffee and Tea" => '☕️',
    Colombian: '🇨🇴',
    Creole: '🍊',
    Crepes: '🍌',
    Cuban: '🇨🇺',
    Danish: '🇩🇰',
    Deli: '🥩',
    Desserts: '🍧',
    :"Dim Sum" => '🍲',
    Diner: '🥞',
    Dominican: '🇩🇴',
    Donuts: '🍩',
    :"Drinks Only" => '🍸',
    :"Eastern European" => '🏰',
    Ecuadorian: '🇪🇨',
    Ethiopian: '🇪🇹',
    European: '🇪🇺',
    :"Fast Food" => '🌭',
    Filipino: '🇵🇭',
    :"Fish and Chips" => '🐟',
    Fondue: '🍓',
    French: '🇫🇷',
    :"Frozen Yogurt" => '🐮',
    Fusion: '🍥',
    Georgian: '🇬🇪',
    German: '🇩🇪',
    Greek: '🇬🇷',
    Hawaiian: '🏝',
    :"Healthy Food" => '🍎',
    Hungarian: '🇭🇺',
    :"Ice Cream" => '🍦',
    Indian: '🇮🇳',
    Indonesian: '🇮🇩',
    International: '🌍',
    Iranian: '🇮🇷',
    Irish: '🇮🇪',
    Israeli: '🇮🇱',
    Italian: '🇮🇹',
    Jamaican: '🇯🇲',
    Japanese: '🇯🇵',
    Jewish: '🕍',
    Juices: '🥤',
    Kebab: '🥩',
    Korean: '🇰🇷',
    Laotian: '🇱🇦',
    :"Latin American" => '🌮',
    Lebanese: '🇱🇧',
    Malaysian: '🇲🇾',
    Mediterranean: '🥙',
    Mexican: '🇲🇽',
    :"Middle Eastern" => '🥙',
    Mongolian: '🇲🇳',
    Moroccan: '🇲🇦',
    Mughlai: '🍒',
    Nepalese: '🇳🇵',
    :"New American" => '🏈',
    :"New Mexican" => '🌮',
    :"New Zealand" => '🇳🇿',
    Nicaraguan: '🇳🇮',
    Pacific: '🍏',
    :"Pacific Northwest" => '🍠',
    Pakistani: '🇵🇰',
    Patisserie: '🍰',
    Peruvian: '🇵🇪',
    Pizza: '🍕',
    :"Po'Boys" => '🥑',
    Polish: '🇵🇱',
    Portuguese: '🇵🇹',
    :"Pub Food" => '🍺',
    :"Puerto Rican" => '🇵🇷',
    Ramen: '🍜',
    Russian: '🇷🇺',
    Salad: '🥗',
    Salvadorean: '🇸🇻',
    Sandwich: '🥪',
    Scandinavian: '🥝',
    Scottish: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    Seafood: '🐙',
    Sichuan: '🍱',
    Singaporean: '🇸🇬',
    Somali: '🇸🇴',
    :"Soul Food" => '👵🏾',
    :"South African" => '🇿🇦',
    :"South American" => '🌶',
    Southern: '🥕',
    Southwestern: '🍇',
    Spanish: '🇪🇸',
    :"Sri Lankan" => '🇱🇰',
    Steak: '🥩',
    Sushi: '🍣',
    Swedish: '🇸🇪',
    Taco: '🌮',
    Taiwanese: '🇹🇼',
    Tapas: '🍤',
    Tea: '🍵',
    Teriyaki: '🍲',
    :"Tex-Mex" => '🍈',
    Thai: '🇹🇭',
    Tibetan: '🌽',
    Tunisian: '🇹🇳',
    Turkish: '🇹🇷',
    Ukrainian: '🇺🇦',
    Uruguayan: '🇺🇾',
    Vegetarian: '🥦',
    Venezuelan: '🇻🇪',
    Vietnamese: '🇻🇳',
    Welsh: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  }

  def self.cuisine_to_icon_hash
    @cuisine_to_icon_hash
  end
end
