:concurrency:
  <%= ENV.fetch("SIDEKIQ_WORKER_COUNT") { 1 } %>
:queues:
  - ["critical", <%= ENV.fetch("CRITICAL_QUEUE_WEIGHT") { 2 } %>]
  - ["default",  <%= ENV.fetch("DEFAULT_QUEUE_WEIGHT") { 1 } %>]
  - 'deliveries'
