#!/bin/sh
set -e
cd "$(dirname "$0")/.."

bp-we-eat_NAME=$1
bp-we-eat_PORT=$2
APP_NAME=`echo ${bp-we-eat_NAME} | perl -pe 's/(^|_)./uc($&)/ge;s/_//g'`

if [ -z "$bp-we-eat_PORT" ]
then
  echo "No port supplied. Usage: script/initialize bp-we-eat_NAME bp-we-eat_PORT"
  exit 1
fi

if [ -z "$bp-we-eat_NAME" ]
then
  echo "No project name supplied. Usage: script/initialize bp-we-eat_NAME bp-we-eat_PORT"
  exit 1
fi

find docker-compose.yml -type f -exec perl -pi -e "s/bp-we-eat_PORT/${bp-we-eat_PORT}/g" {} \;
find config/application.rb -type f -exec  perl -pi -e "s/bp-we-eat/${APP_NAME}/g" {} \;
find . -type f -not -path "*.git*" -not -path "script/initialize" -exec  perl -pi -e "s/bp-we-eat/${bp-we-eat_NAME}/g" {} \;

docker run --rm -v "$PWD":/app -w /app ruby:2.5.1 bundle install
docker build . -t quay.io/wework/${bp-we-eat_NAME}:master
docker push quay.io/wework/${bp-we-eat_NAME}:master
