#!/bin/sh
set -e
cd "$(dirname "$0")/.."

docker-compose up -d pg redis rabbitmq spring backend frontend jobs delivery_listener
docker attach $(docker-compose ps -q backend)
docker-compose stop backend frontend jobs delivery_listener
