#!/bin/sh
set -e
cd "$(dirname "$0")/.."

docker-compose -f docker-compose.test.yml up -d pg spring

if [ $# -eq 0 ]; then {
    docker-compose -f docker-compose.test.yml run --rm test
} else {
    docker-compose -f docker-compose.test.yml run --rm test bin/rspec "$@"
} fi
