#!/bin/sh
set -e
cd "$(dirname "$0")/.."

script/bootstrap
docker-compose up -d pg spring
docker-compose run base bin/rails db:migrate
docker-compose -f docker-compose.test.yml up -d pg spring
docker-compose -f docker-compose.test.yml run test rails db:migrate db:test:prepare

docker-compose -f docker-compose.yml build frontend